- name: Install utils to nodes
  hosts: docker_nodes
  remote_user: sumgan
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: Update apt-cache
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Install requirements
    apt:
      name:
      - python3
      - python3-pip
      state: latest

  - name: Install docker SDK for python
    pip:
      - docker