apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
    - protocol: TCP
      port: 80
  externalIPs:
    - 172.19.0.36
    - 172.19.0.37
    - 172.19.0.38
    - 172.19.0.39